name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: Backend/package-lock.json

      - name: Install Backend dependencies
        working-directory: Backend
        run: npm install

      - name: Restart Backend
        run: sudo pm2 restart backend
